[package]
name = "ish"
version = "0.1.0"
edition = "2021"
authors = ["9494 <Brucexuheng@163.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
prost = "0.5"

[build-dependencies]
prost-build = "0.5"
